<a href="https://colab.research.google.com/github/kovald/API/blob/main/jupiter_seo_shakin.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Тут лежат всякие API ключики, которые нельзя показывать

In [ ]:
#SPOILER

from a_parser import AParser

API_KEY = ""
ACCESS_TOKEN = ''
COUNTER_ID = ''
APARSER_9092 = AParser('')

ModuleNotFoundError: No module named 'a_parser'

# Номер 1 инструмент SEO Специалиста

## Как я пришел к PJNPA

## Что почитать Jupiter Notebook:
* <a href="https://jupyter.org/"> 🚀 Официальный сайт  </a>
* <a href="https://code.visualstudio.com/docs/datascience/jupyter-notebooks"> ❄️ плагин для VS Code </a>
* <a href="https://www.jetbrains.com/help/pycharm/jupyter-notebook-support.html"> 🌡 Плагин для PyCharm  </a>
* <a href="https://colab.research.google.com/"> 👯‍♀️ Google Collab  </a>

<div class="alert alert-custom" style="max-width: 55%; padding:10px; border-width:3px; border-color:#efe6ef; border-style:solid; border-radius:6px">

Просто надо погуглить

## Что нужно чтобы начать

In [ ]:
import pandas as pd

## Почему тут не подходят Python скрипты

### Работа со входными данными

### Скорость работы

### Работа с буфером обмена

In [ ]:
df_ws = pd.read_clipboard()

PyperclipException:
    Pyperclip could not find a copy/paste mechanism for your system.
    For more information, please visit
    https://pyperclip.readthedocs.io/en/latest/index.html#not-implemented-error

In [ ]:
df_ws.to_clipboard()
df_ws.head()

NameError: name 'df_ws' is not defined

In [ ]:
df_pos = pd.read_clipboard()

In [ ]:
df_pos.to_clipboard()
df_pos.head()

### Работа с результатами

In [ ]:
df_ws.merge(df_pos, on='query').to_clipboard()
df_ws.merge(df_pos, on='query').head()

### Работа с результатами ChatGPT и прочих LLM

In [ ]:
def clean_for_cp1251(text):
    try:
        return text.encode('cp1251', errors='ignore').decode('cp1251')
    except Exception:
        return text

df_ws = df_ws.applymap(lambda x: clean_for_cp1251(x) if isinstance(x, str) else x)
df_ws.to_csv('cleaned.csv', index=False, encoding='cp1251')

### Где тут автоматизация?

## N8N? Подвинься

## Sitemap.xml работаем с картой сайта

In [ ]:
pd.options.display.max_colwidth = 100

In [ ]:
df_sitemaps = pd.read_xml(f'https://market.yandex.ru/sitemap/sitemap-all-offers.xml')
df_sitemaps

                                                               loc
0   https://market.yandex.ru/sitemap/sitemap-all-offers-000.xml.gz
1   https://market.yandex.ru/sitemap/sitemap-all-offers-001.xml.gz
2   https://market.yandex.ru/sitemap/sitemap-all-offers-002.xml.gz
3   https://market.yandex.ru/sitemap/sitemap-all-offers-003.xml.gz
4   https://market.yandex.ru/sitemap/sitemap-all-offers-004.xml.gz
5   https://market.yandex.ru/sitemap/sitemap-all-offers-005.xml.gz
6   https://market.yandex.ru/sitemap/sitemap-all-offers-006.xml.gz
7   https://market.yandex.ru/sitemap/sitemap-all-offers-007.xml.gz
8   https://market.yandex.ru/sitemap/sitemap-all-offers-008.xml.gz
9   https://market.yandex.ru/sitemap/sitemap-all-offers-009.xml.gz
10  https://market.yandex.ru/sitemap/sitemap-all-offers-010.xml.gz
11  https://market.yandex.ru/sitemap/sitemap-all-offers-011.xml.gz
12  https://market.yandex.ru/sitemap/sitemap-all-offers-012.xml.gz
13  https://market.yandex.ru/sitemap/sitemap-all-offers-013.xml.gz
14  https://market.yandex.ru/sitemap/sitemap-all-offers-014.xml.gz
15  https://market.yandex.ru/sitemap/sitemap-all-offers-015.xml.gz
16  https://market.yandex.ru/sitemap/sitemap-all-offers-016.xml.gz
17  https://market.yandex.ru/sitemap/sitemap-all-offers-017.xml.gz
18  https://market.yandex.ru/sitemap/sitemap-all-offers-018.xml.gz
19  https://market.yandex.ru/sitemap/sitemap-all-offers-019.xml.gz
20  https://market.yandex.ru/sitemap/sitemap-all-offers-020.xml.gz
21  https://market.yandex.ru/sitemap/sitemap-all-offers-021.xml.gz
22  https://market.yandex.ru/sitemap/sitemap-all-offers-022.xml.gz
23  https://market.yandex.ru/sitemap/sitemap-all-offers-023.xml.gz
24  https://market.yandex.ru/sitemap/sitemap-all-offers-024.xml.gz
25  https://market.yandex.ru/sitemap/sitemap-all-offers-025.xml.gz
26  https://market.yandex.ru/sitemap/sitemap-all-offers-026.xml.gz
27  https://market.yandex.ru/sitemap/sitemap-all-offers-027.xml.gz
28  https://market.yandex.ru/sitemap/sitemap-all-offers-028.xml.gz
29  https://market.yandex.ru/sitemap/sitemap-all-offers-029.xml.gz
30  https://market.yandex.ru/sitemap/sitemap-all-offers-030.xml.gz
31  https://market.yandex.ru/sitemap/sitemap-all-offers-031.xml.gz
32  https://market.yandex.ru/sitemap/sitemap-all-offers-032.xml.gz
33  https://market.yandex.ru/sitemap/sitemap-all-offers-033.xml.gz
34  https://market.yandex.ru/sitemap/sitemap-all-offers-034.xml.gz
35  https://market.yandex.ru/sitemap/sitemap-all-offers-035.xml.gz
36  https://market.yandex.ru/sitemap/sitemap-all-offers-036.xml.gz
37  https://market.yandex.ru/sitemap/sitemap-all-offers-037.xml.gz
38  https://market.yandex.ru/sitemap/sitemap-all-offers-038.xml.gz
39  https://market.yandex.ru/sitemap/sitemap-all-offers-039.xml.gz
40  https://market.yandex.ru/sitemap/sitemap-all-offers-040.xml.gz
41  https://market.yandex.ru/sitemap/sitemap-all-offers-041.xml.gz
42  https://market.yandex.ru/sitemap/sitemap-all-offers-042.xml.gz
43  https://market.yandex.ru/sitemap/sitemap-all-offers-043.xml.gz
44  https://market.yandex.ru/sitemap/sitemap-all-offers-044.xml.gz
45  https://market.yandex.ru/sitemap/sitemap-all-offers-045.xml.gz
46  https://market.yandex.ru/sitemap/sitemap-all-offers-046.xml.gz
47  https://market.yandex.ru/sitemap/sitemap-all-offers-047.xml.gz
48  https://market.yandex.ru/sitemap/sitemap-all-offers-048.xml.gz
49  https://market.yandex.ru/sitemap/sitemap-all-offers-049.xml.gz

In [ ]:
url_df = pd.DataFrame()

for sitemap in df_sitemaps['loc'][:5]:
    print(sitemap)
    df_temp_1 = pd.read_xml(sitemap)
    df_temp_1['sitemap'] = sitemap
    pd.set_option('display.max_colwidth', None)
    url_df = pd.concat([url_df, df_temp_1])

https://market.yandex.ru/sitemap/sitemap-all-offers-000.xml.gz
https://market.yandex.ru/sitemap/sitemap-all-offers-001.xml.gz
https://market.yandex.ru/sitemap/sitemap-all-offers-002.xml.gz
https://market.yandex.ru/sitemap/sitemap-all-offers-003.xml.gz
https://market.yandex.ru/sitemap/sitemap-all-offers-004.xml.gz

In [ ]:
url_df

,loc,changefreq,priority,sitemap
0,https://market.yandex.ru/p/-40-g-12/1863839666/102024809789,always,1,https://market.yandex.ru/sitemap/sitemap-all-offers-000.xml.gz
1,https://market.yandex.ru/p/-pks20h-165a1/1951396794/4532040552,always,1,https://market.yandex.ru/sitemap/sitemap-all-offers-000.xml.gz
2,https://market.yandex.ru/p/-ww500-halle-904/649990402/101091627137,always,1,https://market.yandex.ru/sitemap/sitemap-all-offers-000.xml.gz
3,https://market.yandex.ru/p/0-250-403-001/1772811396/1490849047,always,1,https://market.yandex.ru/sitemap/sitemap-all-offers-000.xml.gz
4,https://market.yandex.ru/p/0-258-005-726/1772810710/870941868,always,1,https://market.yandex.ru/sitemap/sitemap-all-offers-000.xml.gz
...,...,...,...,...
8256,https://market.yandex.ru/p/zubr-tip-5-shag-0325-paz-15-mm-40-sm-shina-dlya-benzopil-70205-40/1778084253/101827944944,always,1,https://market.yandex.ru/sitemap/sitemap-all-offers-004.xml.gz
8257,https://market.yandex.ru/p/zubr-zashchitnyye-prozrachnyye-ochki-zubr-proton-linza-uvelichennogo-razmera-otkrytogo-tipa-110481/1275016325/101859375083,always,1,https://market.yandex.ru/sitemap/sitemap-all-offers-004.xml.gz
8258,https://market.yandex.ru/p/zvezda-227149/834341174/101184366932,always,1,https://market.yandex.ru/sitemap/sitemap-all-offers-004.xml.gz
8259,https://market.yandex.ru/p/zvezdnyy-proyektor-astroplanetariy-detskiy/1155193366/4378657450,always,1,https://market.yandex.ru/sitemap/sitemap-all-offers-004.xml.gz
8260,https://market.yandex.ru/p/zvonok-gromkogo-boya-andeli-sb1-75mm-220v-ip20-adl11-020/1824750464/101859709223,always,1,https://market.yandex.ru/sitemap/sitemap-all-offers-004.xml.gz

## ВПР? Whaat? 😅

## Подключаем любые API

In [ ]:
# Что нужно для работы с любым API

import requests

## Практика — работаем с API Метрики

In [ ]:
# pip install --upgrade tapi-yandex-metrika==2020.10.20

from datetime import datetime, timedelta
import time
from tapi_yandex_metrika import YandexMetrikaStats

api = YandexMetrikaStats(access_token=ACCESS_TOKEN)

In [ ]:
dt_start = '2024-12-01'
dt_end = '2024-12-31'

daterange = pd.date_range(dt_start, dt_end)

daterange

## Сэмпилирование в метрике? Не слышал

In [ ]:
df_week = pd.DataFrame()

for single_date in daterange[:3]:
    params_listQueries = dict(
        ids=COUNTER_ID,
        metrics="ym:s:visits",
        dimensions="ym:s:startURL,ym:s:Date",
        date1 = single_date.strftime("%Y-%m-%d"),
        date2 = single_date.strftime("%Y-%m-%d"),
        limit=100000,
        receive_all_data=True,
        accuracy=1
        )
    while True:
        try:
            result = api.stats().get(params=params_listQueries)
            data = result().transform()
            data[0]
            df = pd.DataFrame(data, columns = data[0])[1:]
            df_week = pd.concat([df_week, df])
            time.sleep(5)
        except Exception:
            continue
        else:
            break

In [ ]:
df_week

In [ ]:
df_week['ym:s:startURL'] = df_week['ym:s:startURL'].astype(str)
df_week['ym:s:startURL'] = df_week['ym:s:startURL'].str.split('#').str[0]
df_week['ym:s:startURL'] = df_week['ym:s:startURL'].str.split('\?utm').str[0]
df_week['ym:s:startURL'] = df_week['ym:s:startURL'].str.split('<br>').str[0]
df_week['ym:s:startURL'] = df_week['ym:s:startURL'].str.split(',%').str[0]
df_week['ym:s:startURL'] = df_week['ym:s:startURL'].str.split('\?').str[0]

In [ ]:
df_week.groupby(['ym:s:startURL'], as_index=False)\
    .agg({'ym:s:visits': 'sum'})

## Быстро получить отчет проще чем кажется

In [ ]:
df_week = pd.DataFrame()
df = pd.DataFrame()


api = YandexMetrikaStats(access_token=ACCESS_TOKEN)

params_listQueries = dict(
    ids=COUNTER_ID,
    metrics="ym:s:users",
    dimensions="ym:s:Year,ym:s:Month,ym:s:lastSearchEngineRoot",
    # dimensions="ym:s:startURL,ym:s:Date,ym:s:lastTrafficSource",
    # dimensions="ym:s:startURL",
    #sort="ym:s:date",
    date1 = dt_start,
    date2 = dt_end,
    # filters=f"ym:s:startURL=@'/pro/'",
    filters=f"ym:s:lastTrafficSource=='organic'",
    # filters=f"ym:s:visits>5",
    limit=100000,
    receive_all_data=True,
    accuracy=1
    )


result = api.stats().get(params=params_listQueries)
data = result().transform()
data[0]
df = pd.DataFrame(data, columns = data[0])[1:]

## Получаем поисковые фразы

In [ ]:
df_week = pd.DataFrame()

for single_date in daterange:
    params_listQueries = dict(
        ids=COUNTER_ID,
        metrics="ym:s:visits",
        dimensions="ym:s:Date,ym:s:lastSearchPhrase",
        date1 = single_date.strftime("%Y-%m-%d"),
        date2 = single_date.strftime("%Y-%m-%d"),
        limit=100000,
        receive_all_data=True,
        accuracy=1
    )


    params_listQueries_2 = dict(
        ids=COUNTER_ID,
        metrics="ym:s:visits",
        dimensions="ym:s:Date,ym:s:lastSearchPhrase",
        date1 = single_date.strftime("%Y-%m-%d"),
        date2 = single_date.strftime("%Y-%m-%d"),
        limit=100000,
        receive_all_data=True,
        accuracy=1,
        offset=100001
    )

    params_listQueries_3 = dict(
        ids=COUNTER_ID,
        metrics="ym:s:visits",
        dimensions="ym:s:Date,ym:s:lastSearchPhrase",
        date1 = single_date.strftime("%Y-%m-%d"),
        date2 = single_date.strftime("%Y-%m-%d"),
        limit=100000,
        receive_all_data=True,
        accuracy=1,
        offset=200001
    )

    params_listQueries_4 = dict(
        ids=COUNTER_ID,
        metrics="ym:s:visits",
        dimensions="ym:s:Date,ym:s:lastSearchPhrase",
        date1 = single_date.strftime("%Y-%m-%d"),
        date2 = single_date.strftime("%Y-%m-%d"),
        limit=100000,
        receive_all_data=True,
        accuracy=1,
        offset=300001
    )


    params_listQueries_5 = dict(
        ids=COUNTER_ID,
        metrics="ym:s:visits",
        dimensions="ym:s:Date,ym:s:lastSearchPhrase",
        date1 = single_date.strftime("%Y-%m-%d"),
        date2 = single_date.strftime("%Y-%m-%d"),
        limit=100000,
        receive_all_data=True,
        accuracy=1,
        offset=400001
    )

    params_listQueries_6 = dict(
        ids=COUNTER_ID,
        metrics="ym:s:visits",
        dimensions="ym:s:Date,ym:s:lastSearchPhrase",
        date1 = single_date.strftime("%Y-%m-%d"),
        date2 = single_date.strftime("%Y-%m-%d"),
        limit=100000,
        receive_all_data=True,
        accuracy=1,
        offset=500001
    )



    # try:
    result = api.stats().get(params=params_listQueries)
    data = result().transform()
    data[0]
    df = pd.DataFrame(data, columns = data[0])[1:]
    df_week = pd.concat([df, df_week], ignore_index=True)
    time.sleep(4)
    print(single_date.strftime("%Y-%m-%d") + " 1")
    # except:
    #     continue


    try:
        result = api.stats().get(params=params_listQueries_2)
        data = result().transform()
        data[0]
        df = pd.DataFrame(data, columns = data[0])[1:]
        df_week = pd.concat([df, df_week], ignore_index=True)
        time.sleep(4)
        print(single_date.strftime("%Y-%m-%d") + " 2")
    except:
        continue


    try:
        result = api.stats().get(params=params_listQueries_3)
        data = result().transform()
        data[0]
        df = pd.DataFrame(data, columns = data[0])[1:]
        df_week = pd.concat([df, df_week], ignore_index=True)
        time.sleep(4)
        print(single_date.strftime("%Y-%m-%d") + " 3")
    except:
        continue


    try:
        result = api.stats().get(params=params_listQueries_4)
        data = result().transform()
        data[0]
        df = pd.DataFrame(data, columns = data[0])[1:]
        df_week = pd.concat([df, df_week], ignore_index=True)
        time.sleep(4)
        print(single_date.strftime("%Y-%m-%d") + " 4")
    except:
        continue


    try:
        result = api.stats().get(params=params_listQueries_5)
        data = result().transform()
        data[0]
        df = pd.DataFrame(data, columns = data[0])[1:]
        df_week = pd.concat([df, df_week], ignore_index=True)
        time.sleep(4)
        print(single_date.strftime("%Y-%m-%d") + " 5")
    except:
        continue


    try:
        result = api.stats().get(params=params_listQueries_6)
        data = result().transform()
        data[0]
        df = pd.DataFrame(data, columns = data[0])[1:]
        df_week = pd.concat([df, df_week], ignore_index=True)
        time.sleep(4)
        print(single_date.strftime("%Y-%m-%d") + " 6")
    except:
        continue

    df_week = df_week.rename(columns={'ym:s:date': 'date', 'ym:s:lastSearchPhrase': 'query', 'ym:s:visits': 'visits'})
    df_week['query'] = df_week['query'].fillna('na')
    df_week['visits'] = df_week['visits'].astype(int)
    df_week['date'] = pd.to_datetime(df_week['date'])


    df_week = pd.DataFrame()

### Ищем толокеров

In [ ]:
df_week = pd.DataFrame()

for single_date in daterange:
    params_listQueries = dict(
        ids=COUNTER_ID,
        metrics="ym:s:visits",
        dimensions="ym:s:startURL,ym:s:Date",
        date1 = single_date.strftime("%Y-%m-%d"),
        date2 = single_date.strftime("%Y-%m-%d"),
        filters=f"ym:s:refererDomain=='iframe-toloka.com'",
        limit=100000,
        receive_all_data=True,
        accuracy=1
        )

    result = api.stats().get(params=params_listQueries)
    data = result().transform()
    data[0]
    df = pd.DataFrame(data, columns = data[0])[1:]
    df_week = pd.concat([df, df_week], ignore_index=True)
    time.sleep(5)

## Взаимодействуем с внешними людьми

In [ ]:
temp_df = pd.read_clipboard()
temp_df

In [ ]:
import pygsheets

gc = pygsheets.authorize(service_account_file='sa_keys_sheets.json')


sh = gc.sheet.create(temp_df.iloc[1]['query'])
sh_o = gc.open(temp_df.iloc[1]['query'])
ws = sh_o[0]



ws.set_dataframe(temp_df,(1,1))
ws.update_value(f'A{len(temp_df) + 3}', "Тайтл")

ws.update_value(f'C{len(temp_df) + 3}', f"{temp_df.iloc[0]['query']}".capitalize())

ws.update_value(f'A{len(temp_df) + 5}', "Заголовок")

ws.update_value(f'C{len(temp_df) + 5}', f"{temp_df.iloc[0]['query']} в 2025 году".capitalize())

ws.update_value(f'A{len(temp_df) + 7}', "Текст начать")

ws.update_value(f'C{len(temp_df) + 7}', f"{temp_df.iloc[0]['query']}".capitalize())

ws.update_value(f'A{len(temp_df) + 9}', "Убрать из Н2Н3")



sh_o.share('', role='writer', type='anyone')

## Фантазируем с имеющимися знаниями — Получаем ссылки из GSC

In [ ]:
import requests

In [ ]:
import time
pd.set_option('display.max_colwidth', None)


cookies = {'enwiki_session': 'SIDCC=AKEyXzWsrYlju-_-8j-b-pDdWDYP6rDbtQs0sBUOd_dAgymUE296tu2DCaur8TzhXM_HRmUHCLU; expires=Tue, 01-Jul-2025 14:30:20 GMT; path=/; domain=.google.com; priority=high'}


headers = {
    "cookie": "_ga=GA1.2-2.981093604.1692179323; _ga=GA1.3-2.981093604.1692179323; _ga=GA1.1-2.981093604.1692179323; _gid=GA1.2-2.1026896545.1721235465; _ga_MKSWTKHW3M=GS1.1.1699458670.1.0.1699458682.0.0.0; ANID=AHWqTUno3AU2kyX1eIgMsStCQhwJayfZ6yGJlkpr62UO5kPRaSMqSQgTn_nEAdbF; _ga=GA1.1.981093604.1692179323; __Secure-BUCKET=CPoF; ADS_VISITOR_ID=00000000-0000-0000-0000-000000000000; HSID=AjGpn7NaiEdPZ4BB3; SSID=A-43y7Ql6kCJQivD8; APISID=YWFPS4cUOZBG8ft0/AUgWwUNB9zdLi2TL-; SAPISID=4OtjfBqGqCRTIZ9P/Aht8fQqe3PPZCsUGo; __Secure-1PAPISID=4OtjfBqGqCRTIZ9P/Aht8fQqe3PPZCsUGo; __Secure-3PAPISID=4OtjfBqGqCRTIZ9P/Aht8fQqe3PPZCsUGo; SID=g.a000lQiKYxxXUsahOmn_mne-VN5KvqI171uwcFChdaV55YzEJJb7B5Z2uOZNlbwq1fKnZHdi5AACgYKAbISAQASFQHGX2MiHs6QCHZSQCBJwD1Y0oEZtBoVAUF8yKq1lHwfnePHYO5QeUMGwiOg0076; __Secure-1PSID=g.a000lQiKYxxXUsahOmn_mne-VN5KvqI171uwcFChdaV55YzEJJb7j8WM_NNUbx--greG_Lc_CQACgYKAUgSAQASFQHGX2Mig_GYWwAdiburwYbAT-Z_TBoVAUF8yKobrDtLJVl2zFLa02QZ01a-0076; __Secure-3PSID=g.a000lQiKYxxXUsahOmn_mne-VN5KvqI171uwcFChdaV55YzEJJb7O9XGr4bt_bkPZ3Hee7Ag8AACgYKAS4SAQASFQHGX2MigPIp3tLxDDYn3yEH-ZvN1BoVAUF8yKrQWXYMpGLepYKYsGrw0rEw0076; SEARCH_SAMESITE=CgQIyJsB; OTZ=7636958_44_44_123780_40_436260; S=billing-ui-v3=cF-wcqboU7ghjoEXqhI9bpVcjrv2rXVU:billing-ui-v3-efe=cF-wcqboU7ghjoEXqhI9bpVcjrv2rXVU:maestro=QyoMCMs8zmh9y4KnQTpnxq2U0CGWeW35VkbSwGUcfqc; AEC=AVYB7cp7OiILoMhwJvMnsHv8P8epPy2zMEdRKsMydNWmxDhTg0kMzrPlijA; NID=515=E1__-LmL2Ktiux6m29hMxt91ASpShu_u68PH-xWuCs-CNLtIF5YLySlYP5IUj1sqvz31sWm6KW358OeoUw4MA7BCQ-0U_LVIteT6su3dkVZtDipQ4d8Muytp0JjnNLXH2cBDuqFx2mrzoXmmF7yNXtrTgcpIYcdBEx6lSU6n1lCxGLpkoCT5fLSI69aidTVAgbZnNqwauJI8R6WptX4NEdiIRSTY6IF1bMC-6wXBrMZ2iq3CVJmEdnxJmPhpx2FDqQhSnTmWNvAlS74VWEsOjStRlhh2vxT2O7hqAbCI0lIklEe5ba1zVV_z5GezfBsulrNRxUXb7dKw_6P1E-7Vlo2whpKQp410CROR5xyArq5woN_iwvHPerL_IJmaCWF0X6ZzaVJ1kU4eJFULGg; _ga_QX2LK1FZEG=GS1.1.1721235395.398.1.1721235757.0.0.0; __Secure-1PSIDTS=sidts-CjEB4E2dkU2gBdSKDD143jTXiQm2lLXI-wSa4W17xDtXfpX3hZ5Z9uBB3t1wJh9wuXvkEAA; __Secure-3PSIDTS=sidts-CjEB4E2dkU2gBdSKDD143jTXiQm2lLXI-wSa4W17xDtXfpX3hZ5Z9uBB3t1wJh9wuXvkEAA; SIDCC=AKEyXzXhgEGder0caOlX_0gEJWKDNfdNQKQ_R7kfEBi7Serrq9XX0srUozTXDL7JfT2Ed5yWq9LUQg; __Secure-1PSIDCC=AKEyXzXlbs3-qo-tsXSV2DRMycTvpo58K6Jfcb6UCDPIhZecgSoXBl35yvqrMKCRve8mEsDP5fy_wg; __Secure-3PSIDCC=AKEyXzXyQ86ay5iSw7JEPHJ7KSVNBto8YxJWH071pqRRaZXhRX45p4HqRBeOFk8R0qQpn7SC8qQBNA",
}



num = 0

df_gsc = pd.DataFrame()

url_param = 'at=AJDi_MgVhQfoJbiphn3P_zBNmk4S:1719846708056'

for url in urls[150:]:
    url_file = url.replace('/', '_').replace('.', '_').replace(':', '')
    print(url_file, num)
    r = requests.get(f'https://search.google.com/search-console/export/links?resource_id=https%3A%2F%2Fmygadget.ru%2F&type=EXTERNAL&target={url}&domain&request_type=2&at=AJDi_MjdEFmaXxuC6VLhaX6wBWxP:1721235458924', allow_redirects=True, headers=headers)
    open(f'donors/{url_file}_gsc_domain.csv', 'wb').write(r.content)
    temp_df = pd.read_csv(f'donors/{url_file}_gsc_domain.csv')
    temp_df['mg_url'] = url
    temp_df.to_csv('gsc_test_mg.csv', mode='a')
    # df_gsc = pd.concat([df_gsc, temp_df])
    num += 1
    time.sleep(3)

## Сроим процессы в SEO, а не регламенты

Которые никто не может проверить

## Нужно ли тут знать Python

Для скорости работы — да

## Финал и домашнее задание

- получить API ключ метрики и ID всех ваших проектов
- получить файлы авторизации в GSC всех ваших проектов
- Сделать OAUTH авторизацию для API доступов в вебмастер яндекса
- Выгрузить данные по этим API за последний год
- покрутить их с помощью .groupby() и .merge(), на выявление каннибализации

Опционально:
- Купить апарсер (если его еще нет) промокод — SHILOV-30$-OFF
— Поставить на отслеживание позиций вашего сайта все выгруженные запросы на протяжении недели-двух
- Объеденить все результаты в один DataFrame и с помощью .groupby() и .merge(), на выявление каннибализации